remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
title: HDL Homey App
description: The unoffical HDL SmartBus app for Homey
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - CODE_OF_CONDUCT.md
  - CONNECTING.md
  - CONTRIBUTING.md
  - DEVICES_CURTAINS.md
  - DEVICES_DIMMERS.md
  - DEVICES_FLOORHEATERS.md
  - DEVICES_MULTISENSORS.md
  - DEVICES_RELAYS.md
  - DEVICES_TEMPSENSORS.md
  - DEVICES_UVSWITCHES.md
  - DEVICES_PANELS.md
